### ISSUE TITLE
Shouldn't it be (W[1,0] * x2 + W[1,1] * y2 + W[1,2])?

### ISSUE THREAD

**Issue by fnuabhimanyu** [ziliHarvey/Lucas-Kanade-tracking-and-Correlation-Filters#2]
https://github.com/ziliHarvey/Lucas-Kanade-tracking-and-Correlation-Filters/blob/9caca36c318351793fa0ff40d4d110b82ab4a39d/src/LucasKanadeAffine.py#L27

**Comment by ziliHarvey** [comment]
Thanks for pointing it out and definitely you are correct. I've updated related code and demo result.

**Comment by fnuabhimanyu** [comment]
Thanks for resolving the issue.
